# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stats_window(object):
    def setupUi(self, stats_window):
        stats_window.setObjectName("stats_window")
        stats_window.resize(544, 481)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Лого.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        stats_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(stats_window)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 20, 351, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 20, 111, 31))
        self.pushButton.setObjectName("pushButton")
        stats_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(stats_window)
        self.statusbar.setObjectName("statusbar")
        stats_window.setStatusBar(self.statusbar)

        self.retranslateUi(stats_window)
        QtCore.QMetaObject.connectSlotsByName(stats_window)

    def retranslateUi(self, stats_window):
        _translate = QtCore.QCoreApplication.translate
        stats_window.setWindowTitle(_translate("stats_window", "Статистика"))
        self.pushButton.setText(_translate("stats_window", "Статистика"))

    def exec_(self):
        pass
