# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stats_window(object):
    def setupUi(self, stats_window):
        stats_window.setObjectName("stats_window")
        stats_window.setWindowModality(QtCore.Qt.NonModal)
        stats_window.resize(430, 435)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stats_window.sizePolicy().hasHeightForWidth())
        stats_window.setSizePolicy(sizePolicy)
        stats_window.setMinimumSize(QtCore.QSize(0, 0))
        stats_window.setMaximumSize(QtCore.QSize(430, 435))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Лого.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        stats_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(stats_window)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.statsTable = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsTable.sizePolicy().hasHeightForWidth())
        self.statsTable.setSizePolicy(sizePolicy)
        self.statsTable.setMinimumSize(QtCore.QSize(401, 351))
        self.statsTable.setMaximumSize(QtCore.QSize(401, 351))
        self.statsTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statsTable.setLineWidth(0)
        self.statsTable.setObjectName("statsTable")
        self.statsTable.setColumnCount(0)
        self.statsTable.setRowCount(0)
        self.gridLayout.addWidget(self.statsTable, 1, 0, 1, 1)
        stats_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(stats_window)
        QtCore.QMetaObject.connectSlotsByName(stats_window)

    def retranslateUi(self, stats_window):
        _translate = QtCore.QCoreApplication.translate
        stats_window.setWindowTitle(_translate("stats_window", "Статистика"))
        self.pushButton.setText(_translate("stats_window", "Статистика"))
